return {
	gopls = {
		analyses = {
			assign = true,
			atomic = true,
			bools = true,
			composites = true,
			copylocks = true,
			deepequalerrors = true,
			embed = true,
			errorsas = true,
			fieldalignment = true,
			httpresponse = true,
			ifaceassert = true,
			loopclosure = true,
			lostcancel = true,
			nilfunc = true,
			nilness = true,
			nonewvars = true,
			printf = true,
			shadow = true,
			shift = true,
			simplifycompositelit = true,
			simplifyrange = true,
			simplifyslice = true,
			sortslice = true,
			stdmethods = true,
			stringintconv = true,
			structtag = true,
			testinggoroutine = true,
			tests = true,
			timeformat = true,
			unmarshal = true,
			unreachable = true,
			unsafeptr = true,
			unusedparams = true,
			unusedresult = true,
			unusedvariable = true,
			unusedwrite = true,
			useany = true,
		},
		hoverKind = "FullDocumentation",
		linkTarget = "pkg.go.dev",
		usePlaceholders = true,
		vulncheck = "Imports",
		hints = {
			assignVariableTypes = true,
			compositeLiteralFields = true,
			constantValues = true,
			functionTypeParameters = true,
			parameterNames = true,
			rangeVariableTypes = true,
		},
	},
}
